FROM openjdk:21

ARG JAR_FILE=/module-api/build/libs/*.jar

#https://bgpark.tistory.com/132

COPY ${JAR_FILE} /deploy.jar

ENV AWS_REGION=ap-northeast-2

ENTRYPOINT ["java","-jar","-Dspring.profiles.active=prod", "/deploy.jar"]
