
server:
  tomcat:
    max-swallow-size: 500MB
  port: 8081
  # shutdown: "graceful"


  config:
    activate:
      on-profile:
        - local

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/todo
    username: sa
    password:
    hikari:
      maximum-pool-size: 5

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate.default_batch_fetch_size: 1000
      hibernate:
        globally_quoted_identifiers: true #DB 예약어도 가능




