
gg:
  jte:
    templateLocation: src/main/kotlin



server:
  tomcat:
    max-swallow-size: 500MB
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  threads:
    virtual:
      enabled: true
  config:
    import:
      - classpath:secret.yml
  devtools:
    livereload:
      enabled: true

  profiles:
    active:
      - local
  application:
    name: free-app
  view-component:
    local-development: false
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.default_batch_fetch_size: 1000
      hibernate:
        globally_quoted_identifiers: true #DB 예약어도 가능
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  config: classpath:logback-free.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"


---

server:

  config:
    activate:
      on-profile:
        - local

spring:
  cloud:
    config:
      enabled: false

  config:
    activate:
      on-profile:
        - local
    import:
      - classpath:secret.yml

  devtools:
    restart:
      poll-interval: 1000
      quiet-period: 900

---

server:
  port: 8081
  config:
    activate:
      on-profile:
        - prod

spring:
  cloud:
    config:
      enabled: false

  config:
    activate:
      on-profile:
        - prod
    import:
      - classpath:secret.yml




---

server:

  config:
    activate:
      on-profile:
        - test

spring:
  cloud:
    config:
      enabled: false

  config:
    activate:
      on-profile:
        - local
    import:
      - classpath:secret.yml
