
gg:
  jte:
    templateLocation: src/main/kotlin



server:
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Iv1.731596c579d3b990
            clientSecret: 1a16900f622b3b74d6d2e1efa40c53a63ad8705d
          google:
            clientId: 700086744673-keplb3hc6ere9uiqddg4aleho4i08g37.apps.googleusercontent.com
            clientSecret: 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
          facebook:
            clientId: 700086744673-keplb3hc6ere9uiqddg4aleho4i08g37.apps.googleusercontent.com
            clientSecret: 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


  profiles:
    active:
      - local
  application:
    name: simple-todo
  view-component:
    local-development: false


logging:
  config: classpath:logback-todo.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"






