
gg:
  jte:
    templateLocation: src/main/kotlin



server:
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  devtools:
    livereload:
      enabled: true

  profiles:
    active:
      - local
  application:
    name: free-app
  view-component:
    local-development: false


logging:
  config: classpath:logback-free.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"






