
gg:
  jte:
    templateLocation: src/main/kotlin

#management:
#  endpoints:
#    web:
#      exposure:
#        include: *

logging:
  level:
    web: debug

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  view-component:
    local-development: false
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/todo
    username: sa
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl









