
server:
  tomcat:
    max-swallow-size: 500MB
  port: 8081
  # shutdown: "graceful"


  config:
    activate:
      on-profile:
        - prod

spring:
  config:
    import:
     - classpath:secret.yml

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  h2:
    console:
      enabled: true
      path: /h2-console



  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.default_batch_fetch_size: 1000
      hibernate:
        globally_quoted_identifiers: true #DB 예약어도 가능
        dialect: org.hibernate.dialect.PostgreSQLDialect


