
gg:
  jte:
    templateLocation: src/main/kotlin



server:
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  profiles:
    active:
      - local
  application:
    name: simple-todo
  view-component:
    local-development: false


logging:
  config: classpath:logback-todo.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"




