spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres
    username: postgres.woawqxzinsnwsvghwanp
    password: kmp0WGpjMssxFZI3
    hikari:
      maximum-pool-size: 5
  security:
    oauth2:
      client:
        registration:
          github:
#            clientId: 9404bfe223cd1d7c01c1
#            clientSecret: 48200e9774f21744648369654a71b069dc6c6753
            clientId: ea007a09c71cae36070b
            clientSecret: c4b5a4b1fc118ed90f7bfb3350b22b5d2ac35859
            redirect-uri: https://www.freeapp.life/login/oauth2/code/github
            scope:
              - user:email
              - read:user
          google:
            clientId: 700086744673-keplb3hc6ere9uiqddg4aleho4i08g37.apps.googleusercontent.com
            clientSecret: asdasd
            scope:
              - email
              - profile
          facebook:
            clientId: 700086744673-keplb3hc6ere9uiqddg4aleho4i08g37.apps.googleusercontent.com
            clientSecret: asdasdasd
            scope:
              - email
              - public_profile


cloud:
  aws:
    credentials:
      access-key: AKIARJVQNPZF3J6NJOWT
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: free-stella
      url: https://free-stella.s3.ap-northeast-2.amazonaws.com/

chrome:
  driver: /Users/stella6767/chromedriver-mac-arm64/chromedriver


# test@6767sp1601!@#

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhiaGxqYmp5aGZpeHBuaG5pdW1uIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwNzYwNzY4MCwiZXhwIjoyMDIzMTgzNjgwfQ.fNcPSkmOXLa4yxrO0lgM58uQzps59MnkjGLQsw3skaU