spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.default_batch_fetch_size: 1000
      hibernate:
        globally_quoted_identifiers: true #DB 예약어도 가능
        format_sql: true
        use_sql_comments: true
        show_sql: true


---

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  config:
    activate:
      on-profile:
        - local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
