@import com.stella.free.entity.Post
@import com.stella.free.view.component.post.PostCardViewComponent
@import org.springframework.data.domain.Page

@param Page<Post> posts
@param PostCardViewComponent postCardViewComponent

<div class="grid grid-cols-4 gap-4">

<%--    @for(Post post : posts.getContent())--%>

<%--        ${postCardViewComponent.render(post)}--%>
<%--        --%>
<%--    @endfor--%>

    <div>asdas</div>
    <div>asdas</div>
    <div>asdas</div>
    <div>asdas</div>
</div>