version: "3"
services:
  test_web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - free_application

  free_application:
    build: .
    expose:
      - 8080
