name: Java CI with Gradle

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: 'Branch to use'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          ref: ${{ github.event.inputs.target-branch }}  # 왜 안 먹히냐...
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew clean build -x test
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: cicdsample
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: cicdsample
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add remote server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      - name: SCP transfer
        run: scp *.jar ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:~/cicd
      - name: Execute remote commands
        run: |
          ssh -v ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "sudo fuser -k 8080/tcp || true"
          ssh -v ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "sudo nohup /usr/bin/java -Djasypt.encryptor.password=1234 -jar ~/cicd/*.jar  > ~/cicd/nohup.log 2>&1 &"   
          # - name: Deploy JAR via SCP
          #   uses: appleboy/scp-action@master
          #   with:
          #     host: ${{ secrets.SERVER_IP }}  # Add your server hostname or IP address to GitHub secrets
          #     username: ${{ secrets.SSH_USER }}  # Add your server username to GitHub secrets       
          #     key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use the SSH private key added to GitHub secrets
          #     source: "./build/libs/*.jar"  # Path to your JAR file
          #     target: "/home/ubuntu/cicd"  # Destination path on the remote server
          
          
          
          # - name: Download artifact
          #   uses: actions/download-artifact@v2
          #   with:
          #     name: cicdsample
          # - name: Setup SSH
          #   uses: webfactory/ssh-agent@v0.5.4
          #   with:
          #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        # - name: WhoamI
        #   run: whoami

      # - name: SCP transfer
      #   run: scp *.jar ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:~/cicd

      # - name: Execute remote commands
      #   run: |
      #     ssh -v ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "sudo fuser -k 8080/tcp || true"
      #     ssh -v ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "sudo nohup /usr/bin/java -jar ~/cicd/*.jar  > ~/cicd/nohup.log 2>&1 &"